### ISSUE TITLE
U need to Change LICENSE to AGPL 3.0v

### ISSUE THREAD

**Issue by Potatoshare88** [zyware/AnyVersion#2]
Because You used my code that is AGPL 3.0v. If need some more explanations. See LICENSE file at https://github.com/MPMDevelopers/PacketHandler

**Comment by zyware** [comment]
@Potatoshare88 Sorry, there are errors in your plugin, I fixed them.

**Comment by zyware** [comment]
What is the problem?
[Imgur](https://i.imgur.com/GOXkgZj.png)

**Comment by zyware** [comment]
I'm going to change everything now.
