### ISSUE TITLE
Why pmmp and not nukkit?

### ISSUE THREAD

**Issue by NycuRO** [zyware/AnyVersion#3]

**Comment by zyware** [comment]
@NycuRO You are reading my mind? I already started it!

**Comment by zyware** [comment]
https://github.com/zyware/AnyVersion/tree/nukkit

**Comment by NycuRO** [comment]
rip nukkit ? ✌️

**Comment by zyware** [comment]
@NycuRO Yes, until they fix the bugs that are known.

**Comment by NycuRO** [comment]
?? what bugs

**Comment by zyware** [comment]
@NycuRO A lot of bugs with crafting. Once Nukkit corrects all errors due to which the normal can not survive, I will return the plug-in support.
