### ISSUE TITLE
Server stopping when older version join in

### ISSUE THREAD

**Issue by Adam1609** [zyware/AnyVersion#7]
Fatal error: Nesting level too deep - recursive dependency? in C:\Users\elite\Desktop\Survival\plugins\AnyVersion-master\src\zyware\AnyVersion\AnyVersion.php on line 174

**Comment by zyware** [comment]
Tell me more, version players, etc.

**Comment by zyware** [comment]
@Adam1609 How to reproduce?

**Comment by Adam1609** [comment]
Using older version to join, depend on what version on, server crashes ten seconds later

**Comment by zyware** [comment]
Which version? PMMP and MCBE?

**Comment by zyware** [comment]
I join with 1.2.7, all okey

**Comment by Adam1609** [comment]
I use latest version of PocketMine and 1.2.10
I use 1.2.8 to join in the server
It disconnected when I join 10 seconds later

Vào 20-02-2018 14:38, "Mikhail N." <notifications@github.com> đã viết:
