### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JamYT** [zyware/AnyVersion#9]
[Server] 19:32:20 INFO > Loading AnyVersion v1.0.2
[Server] 19:32:20 CRITICAL > ParseError: "syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)" (EXCEPTION) in "/AnyVersion_dev-13.phar/src/zyware/AnyVersion/AnyVersion" at line 17
[Server] 19:32:20 EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by zyware** [comment]
@JamYT You use PocketMine-MP latest build API 3.0.0-ALPHA11?

**Comment by JamYT** [comment]
No, I am not. Do you think can link me to where I can get it perhaps?

**Comment by zyware** [comment]
@JamYT No, this plugin works only on PocketMine-MP.
